/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/usr/local/lib/tcc"
#endif
#ifndef CONFIG_TCC_PREDEFS
# define CONFIG_TCC_PREDEFS 1
#endif
#define TCC_VERSION "0.9.27"

#define TCC_VERSION_A 0
#define TCC_VERSION_B 9
#define TCC_VERSION_C 27

#define GCC_MAJOR 7
#define GCC_MINOR 5
#define CC_NAME CC_gcc

#define CONFIG_TCC_STATIC
#define CONFIG_TCC_SEMLOCK 0

