/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/action_open16.png
 * Converted Date: 28/04/2022
 * Icon Last Mod:  28/04/2022
*****************************************/

const IconColor g_action_open16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR__RED,COLOR__RED,COLOR__RED,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR__RED,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR__RED,COLOR__RED,C_TRANSPAR,COLOR__RED,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR__RED,COLOR__RED,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR__RED,COLOR__RED,COLOR__RED,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_WHITE,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,
	COLR_BLACK,CLR_YELLOW,CL_DYELLOW,COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CL_DYELLOW,COLR_BLACK,
	COLR_BLACK,CLR_YELLOW,COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,CL_DYELLOW,COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CL_DYELLOW,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CL_DYELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_action_open16_icon = {
	16, 16, g_action_open16_data
};
