/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/action_save16.png
 * Converted Date: 28/04/2022
 * Icon Last Mod:  28/04/2022
*****************************************/

const IconColor g_action_save16_data[] = {
	COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,CL_DYELLOW,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,CL_DYELLOW,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,CL_DYELLOW,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,CL_DYELLOW,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,
	COLR_BLACK,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,
	C_TRANSPAR,COLR_BLACK,CL_DYELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,CL_DYELLOW,CL_DYELLOW,COLR_BLACK,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,
};

Image g_action_save16_icon = {
	16, 16, g_action_save16_data
};
