/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/box_check.png
 * Converted Date: 06/05/2022
 * Icon Last Mod:  06/05/2022
*****************************************/

const IconColor g_box_check_data[] = {
	COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,
	COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,
};

Image g_box_check_icon = {
	16, 16, g_box_check_data
};
