/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/cabinet16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  27/02/2022
*****************************************/

const IconColor g_cabinet16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_cabinet16_icon = {
	16, 16, g_cabinet16_data
};
