/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/chain_broken16.png
 * Converted Date: 17.05.2023
 * Icon Last Mod:  17.05.2023
*****************************************/

const uint32_t g_chain_broken16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_BLACK,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_BLACK,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_chain_broken16_icon = {
	16, 16, g_chain_broken16_data
};
