/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/chess16.png
 * Converted Date: 23.04.2023
 * Icon Last Mod:  22.04.2023
*****************************************/

const uint32_t g_chess16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,C_TRANSPAR,COLR_LGRAY,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,
	COLR_DGRAY,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,
	COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,
};

Image g_chess16_icon = {
	16, 16, g_chess16_data
};
