/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/clock16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  29/01/2022
*****************************************/

const IconColor g_clock16_data[] = {
	C_TRANSPAR,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,C_TRANSPAR,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_BLACK,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLOR_CYAN,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_clock16_icon = {
	16, 16, g_clock16_data
};
