/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/cscript_file16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  29/01/2022
*****************************************/

const IconColor g_cscript_file16_data[] = {
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR_BLUE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR_BLUE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,
};

Image g_cscript_file16_icon = {
	16, 16, g_cscript_file16_data
};
