/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/desktop16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  25/01/2022
*****************************************/

const IconColor g_desktop16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,
	COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,CLR_YELLOW,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,
	COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,CLR_YELLOW,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,
	COLR_BLACK,COLR_WHITE,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLOR__RED,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,
	COLR_BLACK,COLR_WHITE,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,
	COLR_BLACK,COLR_WHITE,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_DGRAY,COLR_BLACK,
	COLR_BLACK,COLR_WHITE,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_DGRAY,COLR_LGRAY,COLR_BLACK,COLR_WHITE,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,COLR_BLACK,
	COLR_BLACK,COLR_WHITE,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_DGRAY,COLR_LGRAY,COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,COLR_DGRAY,COLR_BLACK,
	COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,
	COLR_BLACK,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_desktop16_icon = {
	16, 16, g_desktop16_data
};
