/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/devtool16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  27/02/2022
*****************************************/

const IconColor g_devtool16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLR_WHITE,CLR_YELLOW,CL_DYELLOW,CL_DYELLOW,CL_DYELLOW,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,COLOR_DRED,CLR_YELLOW,CLR_YELLOW,CL_DYELLOW,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,CLR_YELLOW,CL_DYELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR_TEAL,COLOR_TEAL,COLR_BLACK,
	COLR_BLACK,COLOR__RED,COLOR_DRED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,CLR_DGREEN,CL_DYELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR_TEAL,COLOR_TEAL,COLR_BLACK,
	C_TRANSPAR,COLR_BLACK,COLOR_DRED,COLOR_DRED,COLR_BLACK,COLR_BLACK,COLR_GREEN,CLR_DGREEN,CLR_DGREEN,COLOR_TEAL,COLR_BLACK,COLR_BLACK,COLOR_CYAN,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLOR_DRED,CLR_DGREEN,COLR_GREEN,COLR_GREEN,CLR_DGREEN,CLR_DGREEN,COLOR_TEAL,COLOR_TEAL,COLOR_CYAN,COLOR_CYAN,COLOR_TEAL,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_devtool16_icon = {
	16, 16, g_devtool16_data
};
