/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/dlgedit16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  20/03/2022
*****************************************/

const IconColor g_dlgedit16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,C_TRANSPAR,
	COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_GREEN,COLR_BLACK,COLR_BLACK,
	COLR_BLACK,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLR_BLACK,CLR_DGREEN,COLR_BLACK,COLR_DGRAY,COLR_BLACK,
	COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLOR_BLUE,COLR_LGRAY,COLOR_BLUE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_LGRAY,COLOR_BLUE,COLR_LGRAY,CL_DYELLOW,CL_DYELLOW,COLR_DGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLOR_BLUE,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_LGRAY,COLOR_BLUE,COLR_LGRAY,COLOR_BLUE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLOR_BLUE,COLR_LGRAY,COLOR_BLUE,COLR_LGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_dlgedit16_icon = {
	16, 16, g_dlgedit16_data
};
