/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/error16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  25/01/2022
*****************************************/

const IconColor g_error16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_WHITE,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_DGRAY,
	COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_DGRAY,
	COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_DGRAY,
	COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_DGRAY,
	C_TRANSPAR,COLR_BLACK,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,
	C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_WHITE,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_WHITE,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_error16_icon = {
	16, 16, g_error16_data
};
