/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/file_properties16.png
 * Converted Date: 28/04/2022
 * Icon Last Mod:  28/04/2022
*****************************************/

const IconColor g_file_properties16_data[] = {
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,
};

Image g_file_properties16_icon = {
	16, 16, g_file_properties16_data
};
