/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/file_image16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  26/04/2022
*****************************************/

const IconColor g_file_image16_data[] = {
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLOR_CYAN,CLR_YELLOW,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,CLR_DGREEN,COLOR_CYAN,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,COLOR_CYAN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLOR_CYAN,CLR_DGREEN,COLOR_CYAN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,CLR_DGREEN,CLR_DGREEN,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,
};

Image g_file_image16_icon = {
	16, 16, g_file_image16_data
};
