/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/folder_settings16.png
 * Converted Date: 06/05/2022
 * Icon Last Mod:  06/05/2022
*****************************************/

const IconColor g_folder_settings16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_WHITE,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,
	COLR_BLACK,COLR_WHITE,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,COLR_WHITE,COLR_BLACK,
	COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_LGRAY,COLR_BLACK,
	COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_BLACK,
	COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_LGRAY,COLR_BLACK,
	COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_LGRAY,COLR_BLACK,
	COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_BLACK,
	COLR_BLACK,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,COLOR_BLUE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLOR_BLUE,COLR_BLACK,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLOR_BLUE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLOR_BLUE,COLR_BLACK,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR_BLUE,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLOR_BLUE,COLR_BLACK,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,
};

Image g_folder_settings16_icon = {
	16, 16, g_folder_settings16_data
};
