/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/fonts16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  19/02/2022
*****************************************/

const IconColor g_fonts16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR_BLUE,COLOR_BLUE,C_TRANSPAR,COLOR_BLUE,COLOR_BLUE,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR_BLUE,C_TRANSPAR,COLR_DGRAY,COLOR_BLUE,COLOR_BLUE,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,COLOR_BLUE,C_TRANSPAR,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,COLOR_BLUE,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLOR_BLUE,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,COLOR_BLUE,C_TRANSPAR,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_DGRAY,COLR_DBLUE,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,COLR_DBLUE,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_DBLUE,C_TRANSPAR,C_TRANSPAR,COLR_DBLUE,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,COLR_DBLUE,COLR_DBLUE,C_TRANSPAR,COLR_DBLUE,C_TRANSPAR,COLOR__RED,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,COLOR__RED,COLOR__RED,COLR_DGRAY,
	C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR__RED,COLOR__RED,COLOR__RED,COLR_DGRAY,
	COLR_BLACK,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLOR__RED,COLOR__RED,COLR_DGRAY,COLOR__RED,COLR_DGRAY,
	C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,COLOR__RED,COLOR__RED,COLR_DGRAY,COLR_DGRAY,COLOR__RED,COLR_DGRAY,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_DGRAY,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR__RED,COLOR__RED,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLOR__RED,COLR_DGRAY,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR__RED,COLOR__RED,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR__RED,COLR_DGRAY,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,
};

Image g_fonts16_icon = {
	16, 16, g_fonts16_data
};
