/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/home16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  29/01/2022
*****************************************/

const IconColor g_home16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CL_DYELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLOR_DRED,COLOR_DRED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CL_DYELLOW,CLR_YELLOW,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,COLOR_DRED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CL_DYELLOW,CLR_YELLOW,COLR_BLACK,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLOR_DRED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CL_DYELLOW,CLR_YELLOW,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CL_DYELLOW,CLR_YELLOW,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,CL_DYELLOW,CLR_YELLOW,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,CL_DYELLOW,CLR_YELLOW,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,
	CL_DYELLOW,CLR_YELLOW,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,
	COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_BLACK,
	C_TRANSPAR,COLR_DGRAY,COLR_WHITE,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLR_WHITE,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_DGRAY,COLR_WHITE,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLR_WHITE,COLOR_DRED,COLOR__RED,COLOR__RED,COLOR_DRED,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_DGRAY,COLR_WHITE,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLR_WHITE,COLOR_DRED,COLOR__RED,COLOR__RED,COLOR_DRED,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_DGRAY,COLR_WHITE,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLR_WHITE,COLOR_DRED,COLOR__RED,COLOR__RED,CLR_YELLOW,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR_DRED,COLOR__RED,COLOR__RED,COLOR_DRED,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR_DRED,COLOR__RED,COLOR__RED,COLOR_DRED,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,
};

Image g_home16_icon = {
	16, 16, g_home16_data
};
