/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/journal16.png
 * Converted Date: 28/04/2022
 * Icon Last Mod:  28/04/2022
*****************************************/

const IconColor g_journal16_data[] = {
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLOR_TEAL,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLOR_CYAN,COLOR_TEAL,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLOR_TEAL,COLOR_CYAN,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
};

Image g_journal16_icon = {
	16, 16, g_journal16_data
};
