/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/notes16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  27/02/2022
*****************************************/

const IconColor g_notes16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR_DRED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR_DRED,COLOR_DRED,CLR_YELLOW,COLOR_DRED,COLOR_DRED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR_DRED,COLOR_DRED,CLR_YELLOW,COLOR_DRED,CLR_YELLOW,COLOR_DRED,COLOR_DRED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR_DRED,COLOR_DRED,CLR_YELLOW,COLOR_DRED,CLR_YELLOW,COLOR_DRED,CLR_YELLOW,COLOR_DRED,COLOR_DRED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLR_BLACK,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,COLR_LGRAY,COLR_WHITE,COLR_BLACK,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_LGRAY,COLR_WHITE,COLR_BLACK,COLOR_DRED,COLOR_DRED,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_LGRAY,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_WHITE,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_LGRAY,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_BLACK,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_notes16_icon = {
	16, 16, g_notes16_data
};
