/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/pipe16.png
 * Converted Date: 22.01.2023
 * Icon Last Mod:  09.12.2022
*****************************************/

const IconColor g_pipe16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,COLR_GREEN,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_GREEN,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,CLR_DGREEN,COLR_GREEN,COLR_GREEN,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_GREEN,COLR_GREEN,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,COLR_GREEN,COLR_GREEN,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,CLR_DGREEN,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,CLR_DGREEN,COLR_GREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,COLR_GREEN,COLR_GREEN,COLR_GREEN,CLR_DGREEN,COLR_GREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,CLR_DGREEN,COLR_GREEN,COLR_GREEN,CLR_DGREEN,COLR_GREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,CLR_DGREEN,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_pipe16_icon = {
	16, 16, g_pipe16_data
};
