/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/properties16.png
 * Converted Date: 28/04/2022
 * Icon Last Mod:  28/04/2022
*****************************************/

const IconColor g_properties16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_DBLUE,COLR_DBLUE,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,CLR_YELLOW,COLR_LGRAY,CLR_YELLOW,COLR_LGRAY,CLR_YELLOW,COLR_LGRAY,COLR_BLACK,COLR_DBLUE,COLR_DBLUE,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,CLR_YELLOW,COLR_BLACK,CLR_YELLOW,COLR_LGRAY,CLR_YELLOW,COLR_LGRAY,CLR_YELLOW,COLR_LGRAY,COLR_DBLUE,COLR_DBLUE,
	COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,CLR_YELLOW,COLR_BLACK,CLR_YELLOW,COLR_BLACK,CLR_YELLOW,COLR_LGRAY,CLR_YELLOW,COLR_LGRAY,CLR_YELLOW,COLR_DBLUE,COLR_DBLUE,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,CLR_YELLOW,COLR_BLACK,CLR_YELLOW,COLR_BLACK,CLR_YELLOW,COLR_LGRAY,CLR_YELLOW,COLR_BLACK,COLR_DBLUE,COLR_DBLUE,
	COLR_BLACK,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_DBLUE,COLR_DBLUE,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_DBLUE,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_properties16_icon = {
	16, 16, g_properties16_data
};
