/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/run16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  04/03/2022
*****************************************/

const IconColor g_run16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,
	C_TRANSPAR,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,
	COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,
	C_TRANSPAR,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_WHITE,COLR_DGRAY,COLR_BLACK,COLR_LGRAY,
	COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_LGRAY,COLR_WHITE,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_DGRAY,COLR_BLACK,COLR_LGRAY,
	C_TRANSPAR,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,COLR_LGRAY,
	COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_BLACK,COLR_LGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_LGRAY,COLR_BLACK,COLR_DGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_DGRAY,COLR_BLACK,COLR_LGRAY,C_TRANSPAR,
	COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_BLACK,COLR_LGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_LGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_run16_icon = {
	16, 16, g_run16_data
};
