/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/sticky_notes16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  26/04/2022
*****************************************/

const IconColor g_sticky_notes16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_CYAN,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,CLR_YELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,COLR_BLACK,COLOR_CYAN,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,COLR_BLACK,COLOR_TEAL,COLR_BLACK,COLR_BLACK,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_BLACK,COLOR_TEAL,COLOR_CYAN,COLOR_CYAN,COLOR_TEAL,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_BLACK,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CL_DYELLOW,COLR_LGRAY,CL_DYELLOW,COLR_BLACK,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_LGRAY,CL_DYELLOW,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_LGRAY,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_BLACK,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CL_DYELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_WHITE,CLR_YELLOW,COLR_WHITE,CLR_YELLOW,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,CLR_YELLOW,COLR_WHITE,COLR_BLACK,CLR_YELLOW,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_sticky_notes16_icon = {
	16, 16, g_sticky_notes16_data
};
