/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/taskbar_dock.png
 * Converted Date: 28.03.2023
 * Icon Last Mod:  28.03.2023
*****************************************/

const uint32_t g_taskbar_dock_data[] = {
	COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,C_TRANSPAR,C_TRANSPAR,
	COLR_LGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	COLR_LGRAY,COLR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	COLR_LGRAY,COLR_WHITE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLOR_BLUE,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLOR_DRED,COLOR__RED,COLOR__RED,COLOR_DRED,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLOR__RED,COLOR__RED,COLOR_DRED,COLOR_DRED,COLOR_DRED,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	COLR_LGRAY,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLOR_DRED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR_DRED,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLOR_DRED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR_DRED,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLOR_DRED,COLOR__RED,COLOR__RED,COLOR_DRED,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLOR_DRED,COLOR_DRED,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,
	COLR_LGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_LGRAY,
	COLR_LGRAY,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,C_TRANSPAR,COLR_LGRAY,
};

Image g_taskbar_dock_icon = {
	16, 16, g_taskbar_dock_data
};
