/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/vb_text_cen.png
 * Converted Date: 22.01.2023
 * Icon Last Mod:  22.01.2023
*****************************************/

const IconColor g_vb_text_cen_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_vb_text_cen_icon = {
	16, 16, g_vb_text_cen_data
};
