/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/view_icon16.png
 * Converted Date: 28/04/2022
 * Icon Last Mod:  28/04/2022
*****************************************/

const IconColor g_view_icon16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLOR_CYAN,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR__RED,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_GREEN,COLR_WHITE,COLR_WHITE,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_WHITE,COLR_WHITE,COLR_WHITE,CLR_YELLOW,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLOR_BLUE,COLR_WHITE,COLR_WHITE,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_WHITE,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_BLACK,C_TRANSPAR,
	COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_view_icon16_icon = {
	16, 16, g_view_icon16_data
};
