/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/whats_this16.png
 * Converted Date: 28/04/2022
 * Icon Last Mod:  28/04/2022
*****************************************/

const IconColor g_whats_this16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,COLR_BLACK,COLOR__RED,COLOR__RED,COLOR__RED,COLR_BLACK,
	C_TRANSPAR,COLR_WHITE,COLR_WHITE,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,
	C_TRANSPAR,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,
	C_TRANSPAR,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_WHITE,COLR_LGRAY,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLOR__RED,COLOR__RED,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_WHITE,COLR_WHITE,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,COLR_BLACK,COLR_BLACK,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_whats_this16_icon = {
	16, 16, g_whats_this16_data
};
