/*****************************************
        NanoShell Operating System
          (c) 2022 iProgramInCpp

  This is a converted icon to embed into
            the kernel image.
 * Converted File: icons/wmenu16.png
 * Converted Date: 26/04/2022
 * Icon Last Mod:  29/03/2022
*****************************************/

const IconColor g_wmenu16_data[] = {
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_DBLUE,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_WHITE,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_LGRAY,COLR_DBLUE,COLR_WHITE,COLR_DBLUE,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_BLACK,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_BLACK,COLR_BLACK,COLR_LGRAY,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_WHITE,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_LGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,COLR_DGRAY,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
	C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,C_TRANSPAR,
};

Image g_wmenu16_icon = {
	16, 16, g_wmenu16_data
};
