/*****************************************
		NanoShell Operating System
	      (C) 2022 iProgramInCpp

      Icon listing module headerfile
******************************************/
#ifndef _ICON_H
#define _ICON_H

#include <main.h>
#include <video.h>

#define COLR_BLACK 0x00000000
#define COLR_DBLUE 0x00000080
#define CLR_DGREEN 0x00008000
#define COLOR_TEAL 0x00008080
#define COLOR_DRED 0x00800000
#define C_DMAGENTA 0x00800080
#define CL_DYELLOW 0x00808000
#define COLR_DGRAY 0x00808080

#define COLR_LGRAY 0x00C0C0C0
#define COLOR_BLUE 0x000000FF
#define COLR_GREEN 0x0000FF00
#define COLOR_CYAN 0x0000FFFF
#define COLOR__RED 0x00FF0000
#define CL_MAGENTA 0x00FF00FF
#define CLR_YELLOW 0x00FFFF00
#define COLR_WHITE 0x00FFFFFF

//WORK: Add in your icons here in this enum:
enum 
{
	ICON_NULL,
	ICON_CABINET,
	ICON_CHIP,
	ICON_CHIP_SQ,
	ICON_COMPUTER,
	ICON_COMPUTER_SHUTDOWN,
	ICON_DESKTOP,
	ICON_DRAW,
	ICON_EARTH,
	ICON_ERROR,
	ICON_EXECUTE_FILE,
	ICON_FILE,
	ICON_FILES,
	ICON_FOLDER,
	ICON_FOLDER_BLANK,
	ICON_FOLDER_MOVE,
	ICON_FOLDER_PARENT,
	ICON_FOLDER16_CLOSED,
	ICON_FOLDER16_OPEN,
	ICON_GLOBE,
	ICON_GO,
	ICON_HAND,
	ICON_HELP,
	ICON_INFO,
	ICON_KEYBOARD,
	ICON_KEYBOARD2,
	ICON_LAPTOP,
	ICON_NOTES,
	ICON_PAINT,
	ICON_SERIAL,
	ICON_STOP,
	ICON_TEXT_FILE,
	ICON_WARNING,
	ICON_NANOSHELL_LETTERS,
	ICON_NANOSHELL_LETTERS16,
	ICON_NANOSHELL,
	ICON_NANOSHELL16,
	ICON_BOMB,
	ICON_BOMB_SPIKEY,
	ICON_FILE16,
	ICON_TEXT_FILE16,
	ICON_EXECUTE_FILE16,
	ICON_FOLDER_PARENT16,
	//icons V1.1
	ICON_FOLDER_SETTINGS,
	ICON_CABINET16,
	ICON_COMPUTER16,
	ICON_COMMAND,
	ICON_COMMAND16,
	ICON_ERROR16,
	//icons V1.2
	ICON_LOCK,
	ICON_DIRECTIONS,
	ICON_CERTIFICATE,
	ICON_FILE_WRITE,
	ICON_SCRAP_FILE,
	ICON_SCRAP_FILE16,
	ICON_RESMON,
	ICON_BILLBOARD,
	ICON_FILE_CSCRIPT,
	ICON_FILE_CSCRIPT16,
	ICON_FILE_CLICK,
	ICON_KEYS,
	ICON_RESTRICTED,
	ICON_HOME,
	ICON_HOME16,
	ICON_ADAPTER,
	ICON_CLOCK,
	ICON_CLOCK16,
	//icons V1.3
	ICON_APPLICATION,
	ICON_APPLICATION16,
	ICON_TASKBAR,
	ICON_APP_DEMO,
	ICON_COMPUTER_FLAT,
	ICON_CALCULATOR,
	ICON_CALCULATOR16,
	ICON_DESKTOP2,
	ICON_MOUSE,
    //Icons V1.31
	ICON_AMBULANCE,
	//icons V1.32
	ICON_FONTS,
	ICON_FONTS16,
	//icons V1.33
	ICON_RESMON16,
	ICON_NOTES16,
	ICON_FILE_NANO,
	//icons V1.34
	ICON_CLOCK_EMPTY,//Special case which draws more stuff
	//icons V1.35
	ICON_RUN,
	ICON_RUN16,
	//icons V1.4
	ICON_DEVTOOL,
	ICON_DEVTOOL_FILE,
	ICON_HEX_EDIT,
	ICON_CHAIN,
	ICON_CHAIN16,
	ICON_DEVTOOL16,
	ICON_TODO,
	ICON_FOLDER_DOCU,
	ICON_DLGEDIT,
	ICON_DESK_SETTINGS,
	ICON_SHUTDOWN,
	ICON_NOTEPAD,
	ICON_FILE_MKDOWN,
	ICON_FILE_MKDOWN16,
	ICON_COMPUTER_PANIC,
	ICON_EXPERIMENT,
	ICON_GRAPH,
	ICON_CABINET_COMBINE,
	ICON_REMOTE,
	ICON_CABINET_OLD,
	//icons V1.5
	ICON_DEVICE_CHAR,
	ICON_DEVICE_BLOCK,
	ICON_HARD_DRIVE,
	ICON_HARD_DRIVE_MOUNT,
	ICON_WINDOW,
	ICON_WINDOW_SNAP,
	ICON_WINDOW_OVERLAP,
	ICON_SWEEP_SMILE,
	ICON_SWEEP_CLICK,
	ICON_SWEEP_DEAD,
	ICON_SWEEP_CARET,
	ICON_DLGEDIT16,
	ICON_BOMB_SPIKEY16,
	ICON_MAGNIFY,
	ICON_MAGNIFY16,
	ICON_TAR_ARCHIVE,
	ICON_SYSMON,
	ICON_SYSMON16,
	ICON_COMPUTER_SHUTDOWN16,
	ICON_EXIT,
	ICON_KEY,
	ICON_KEYB_REP_SPEED,
	ICON_KEYB_REP_DELAY,
	ICON_MONITOR,
	//icons V1.6
	ICON_FILE_INI,
	ICON_WMENU,
	ICON_WMENU16,
	ICON_FILE_IMAGE,
	ICON_FILE_IMAGE16,
	ICON_FILE_LOG,
	ICON_STICKY_NOTES,
	ICON_STICKY_NOTES16,
	ICON_NOTE_YELLOW,
	ICON_NOTE_BLUE,
	ICON_NOTE_GREEN,
	ICON_NOTE_WHITE,
	ICON_FOLDER_OPEN,
	//icons V1.61
	ICON_EXPERIMENT2,
	ICON_FLOPPY, ICON_ACTION_SAVE = ICON_FLOPPY,
	ICON_ACTION_SAVE16,
	ICON_ACTION_OPEN,
	ICON_ACTION_OPEN16,
	ICON_PLUS,
	//icons V1.7
	ICON_PASTE,
	ICON_PASTE16,
	ICON_DELETE,
	ICON_DELETE16,
	ICON_COPY,
	ICON_COPY16,
	ICON_BACK,
	ICON_BACK16,
	ICON_FORWARD,
	ICON_FORWARD16,
	ICON_UNDO,
	ICON_UNDO16,
	ICON_REDO,
	ICON_REDO16,
	ICON_FILE_SEARCH,
	ICON_FILE_SEARCH16,
	ICON_FILE_PROPERTIES,
	ICON_FILE_PROPERTIES16,
	ICON_PROPERTIES,
	ICON_PROPERTIES16,
	ICON_WHATS_THIS,
	ICON_WHATS_THIS16,
	ICON_VIEW_ICON,
	ICON_VIEW_ICON16,
	ICON_VIEW_LIST,
	ICON_VIEW_LIST16,
	ICON_VIEW_TABLE,
	ICON_VIEW_TABLE16,
	ICON_SORT_ALPHA,
	ICON_SORT_ALPHA16,
	ICON_FORM,
	ICON_FORM16,
	ICON_JOURNAL,
	ICON_JOURNAL16,
	ICON_PACKAGER,
	ICON_PACKAGER16,
	//icons V1.71
	ICON_BOX_CHECK,
	ICON_BOX_UNCHECK,
	ICON_FOLDER_SETTINGS16,
	//icons V1.8
	ICON_MINIMIZE,
	ICON_MAXIMIZE,
	ICON_RESTORE,
	ICON_CLOSE,
	ICON_ARROW_UP,
	ICON_ARROW_DOWN,
	ICON_ARROW_LEFT,
	ICON_ARROW_RIGHT,
	ICON_PIPE,
	ICON_PIPE16,
	ICON_VB_CURSOR,
	ICON_VB_SELECT,
	ICON_VB_TEXT,
	ICON_VB_TEXT_CEN,
	ICON_VB_INPUT_1LINE,
	ICON_VB_INPUT_MLINE,
	ICON_VB_CHECKBOX,
	ICON_VB_SURR_RECT,
	ICON_VB_BUTTON,
	ICON_CLIPBOARD,
	ICON_PAINT2,
	ICON_FILE_BROKEN,
	ICON_STOP_BLACK,
	ICON_STOP_SMALL,
	ICON_PAUSE_BLACK,
	ICON_PAUSE_SMALL,
	ICON_PLAY_BLACK,
	ICON_PLAY_SMALL,
	ICON_BROWSE_SMALL,
	ICON_SNAP_U,
	ICON_SNAP_D,
	ICON_SNAP_L,
	ICON_SNAP_R,
	ICON_SNAP_UL,
	ICON_SNAP_UR,
	ICON_SNAP_DL,
	ICON_SNAP_DR,
	ICON_TASKBAR_POPOUT,
	ICON_TASKBAR_DOCK,
	ICON_COUNT
};

typedef int IconType;

/**
 * Gets an icon image.
 */
Image* GetIconImage(IconType type, int sz);

/**
 * Renders an icon to the screen.
 */
void RenderIcon(IconType type, int x, int y);
void RenderIconOutline(IconType type, int x, int y, uint32_t outline);

/**
 * Renders an icon to the screen, forcing it to be a certain size.
 */
void RenderIconForceSize(IconType type, int x, int y, int size);
void RenderIconForceSizeOutline(IconType type, int x, int y, int size, uint32_t color);

#endif//_ICON_H